#!/usr/bin/env python3
"""
AM Demodulator Results Plotter

Description:
    This script visualizes the performance of a Hilbert transform-based AM demodulator
    by analyzing output data from the Vitis HLS testbench. It provides comprehensive
    time-domain, frequency-domain, and error analysis to validate the demodulator's
    functionality and performance.

Input Files (generated by testbench):
    - am_input.dat: Input AM modulated signal (index, amplitude)
    - am_output.dat: Demodulated output signal (index, amplitude)
    - message_signal.dat: Expected message signal for comparison (index, amplitude)

Output:
    Three visualization plots saved as high-resolution PNG images:
    
    1. Time Domain Analysis (am_demod_time_domain.png):
       - Input AM signal showing carrier and envelope modulation
       - Overlay comparison of demodulated output vs expected message
       - Error signal to visualize demodulation accuracy
       
    2. Frequency Domain Analysis (am_demod_frequency_domain.png):
       - FFT magnitude spectrum showing frequency content
       - Power Spectral Density (Welch method) for noise analysis
       - Comparison between demodulated and expected signals
       
    3. Error Analysis (am_demod_error_analysis.png):
       - Error distribution histogram
       - Cumulative absolute error over time
       - Error vs output scatter plot
       - Statistical summary: mean, std dev, max error, RMSE, SNR

Features:
    - Automatic file validation with helpful error messages
    - Skips initial 500 samples to avoid filter transient effects
    - Calculates SNR to quantify demodulation quality
    - Interactive plot display with automatic file saving
    - Professional formatting with labeled axes and legends

Requirements:
    - Python 3.x
    - NumPy: for numerical operations and FFT
    - Matplotlib: for plotting and visualization
    - SciPy: for advanced signal processing (Welch PSD)
    
    Install with: pip install numpy matplotlib scipy

Usage:
    python3 plot_am_results.py
    
    Run this script in the same directory as the .dat files generated
    by the AM demodulator testbench.

Author: Generated for Vitis HLS AM Demodulator Project
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy import signal
import sys
import os

def read_data_file(filename):
    """Read data file with format: index value"""
    try:
        data = np.loadtxt(filename)
        indices = data[:, 0].astype(int)
        values = data[:, 1]
        return indices, values
    except Exception as e:
        print(f"Error reading {filename}: {e}")
        return None, None

def plot_time_domain(indices, am_input, output, message, sample_rate):
    """Plot time domain signals"""
    time = indices / sample_rate * 1000  # Convert to milliseconds
    
    fig, axes = plt.subplots(3, 1, figsize=(12, 10))
    fig.suptitle('AM Demodulator - Time Domain Analysis', fontsize=14, fontweight='bold')
    
    # Plot 1: Input AM Signal
    axes[0].plot(time, am_input, 'b-', linewidth=0.5, label='AM Input')
    axes[0].set_ylabel('Amplitude', fontweight='bold')
    axes[0].set_title('Input AM Modulated Signal')
    axes[0].grid(True, alpha=0.3)
    axes[0].legend()
    axes[0].set_xlim([0, min(50, time[-1])])  # Show first 50ms
    
    # Plot 2: Output vs Expected
    axes[1].plot(time, output, 'r-', linewidth=1.5, label='Demodulated Output', alpha=0.8)
    axes[1].plot(time, message, 'g--', linewidth=1.5, label='Expected Message', alpha=0.7)
    axes[1].set_ylabel('Amplitude', fontweight='bold')
    axes[1].set_title('Demodulated Output vs Expected Message Signal')
    axes[1].grid(True, alpha=0.3)
    axes[1].legend()
    
    # Plot 3: Error Signal
    error = output - message
    axes[2].plot(time, error, 'k-', linewidth=0.8, label='Error')
    axes[2].axhline(y=0, color='gray', linestyle='--', alpha=0.5)
    axes[2].set_xlabel('Time (ms)', fontweight='bold')
    axes[2].set_ylabel('Error', fontweight='bold')
    axes[2].set_title('Demodulation Error')
    axes[2].grid(True, alpha=0.3)
    axes[2].legend()
    
    plt.tight_layout()
    return fig

def plot_frequency_domain(output, message, sample_rate):
    """Plot frequency domain analysis using FFT"""
    fig, axes = plt.subplots(2, 1, figsize=(12, 8))
    fig.suptitle('AM Demodulator - Frequency Domain Analysis', fontsize=14, fontweight='bold')
    
    # Calculate FFT for output
    N = len(output)
    fft_output = np.fft.fft(output)
    fft_message = np.fft.fft(message)
    freqs = np.fft.fftfreq(N, 1/sample_rate)
    
    # Only plot positive frequencies
    pos_mask = freqs >= 0
    freqs_pos = freqs[pos_mask]
    fft_output_pos = np.abs(fft_output[pos_mask])
    fft_message_pos = np.abs(fft_message[pos_mask])
    
    # Plot 1: FFT Magnitude
    axes[0].semilogy(freqs_pos, fft_output_pos, 'r-', linewidth=1.5, 
                     label='Demodulated Output', alpha=0.8)
    axes[0].semilogy(freqs_pos, fft_message_pos, 'g--', linewidth=1.5, 
                     label='Expected Message', alpha=0.7)
    axes[0].set_xlabel('Frequency (Hz)', fontweight='bold')
    axes[0].set_ylabel('Magnitude', fontweight='bold')
    axes[0].set_title('FFT Magnitude Spectrum')
    axes[0].grid(True, alpha=0.3, which='both')
    axes[0].legend()
    axes[0].set_xlim([0, min(10000, sample_rate/2)])  # Show up to 10 kHz
    
    # Plot 2: Power Spectral Density
    f_out, psd_out = signal.welch(output, sample_rate, nperseg=1024)
    f_msg, psd_msg = signal.welch(message, sample_rate, nperseg=1024)
    
    axes[1].semilogy(f_out, psd_out, 'r-', linewidth=1.5, 
                     label='Demodulated Output', alpha=0.8)
    axes[1].semilogy(f_msg, psd_msg, 'g--', linewidth=1.5, 
                     label='Expected Message', alpha=0.7)
    axes[1].set_xlabel('Frequency (Hz)', fontweight='bold')
    axes[1].set_ylabel('PSD (V²/Hz)', fontweight='bold')
    axes[1].set_title('Power Spectral Density')
    axes[1].grid(True, alpha=0.3, which='both')
    axes[1].legend()
    axes[1].set_xlim([0, min(10000, sample_rate/2)])
    
    plt.tight_layout()
    return fig

def plot_error_statistics(output, message):
    """Plot error statistics and histograms"""
    error = output - message
    
    # Skip initial transient (first 500 samples)
    error_steady = error[500:]
    
    fig, axes = plt.subplots(2, 2, figsize=(12, 8))
    fig.suptitle('AM Demodulator - Error Analysis', fontsize=14, fontweight='bold')
    
    # Plot 1: Error histogram
    axes[0, 0].hist(error_steady, bins=50, color='blue', alpha=0.7, edgecolor='black')
    axes[0, 0].set_xlabel('Error', fontweight='bold')
    axes[0, 0].set_ylabel('Count', fontweight='bold')
    axes[0, 0].set_title('Error Distribution')
    axes[0, 0].grid(True, alpha=0.3)
    axes[0, 0].axvline(x=0, color='r', linestyle='--', linewidth=2)
    
    # Plot 2: Cumulative error
    cumulative_error = np.cumsum(np.abs(error))
    axes[0, 1].plot(cumulative_error, 'b-', linewidth=1.5)
    axes[0, 1].set_xlabel('Sample Index', fontweight='bold')
    axes[0, 1].set_ylabel('Cumulative |Error|', fontweight='bold')
    axes[0, 1].set_title('Cumulative Absolute Error')
    axes[0, 1].grid(True, alpha=0.3)
    
    # Plot 3: Error vs Output scatter
    axes[1, 0].scatter(output[500::10], error[500::10], alpha=0.3, s=10)
    axes[1, 0].axhline(y=0, color='r', linestyle='--', linewidth=2)
    axes[1, 0].set_xlabel('Output Value', fontweight='bold')
    axes[1, 0].set_ylabel('Error', fontweight='bold')
    axes[1, 0].set_title('Error vs Output Value')
    axes[1, 0].grid(True, alpha=0.3)
    
    # Plot 4: Statistics text
    axes[1, 1].axis('off')
    
    # Calculate statistics
    mean_error = np.mean(error_steady)
    std_error = np.std(error_steady)
    max_error = np.max(np.abs(error_steady))
    rmse = np.sqrt(np.mean(error_steady**2))
    snr = 10 * np.log10(np.mean(message[500:]**2) / np.mean(error_steady**2))
    
    stats_text = f"""
    Error Statistics (after transient):
    
    Mean Error:        {mean_error:.6f}
    Std Deviation:     {std_error:.6f}
    Max Abs Error:     {max_error:.6f}
    RMSE:              {rmse:.6f}
    SNR:               {snr:.2f} dB
    
    Samples Analyzed:  {len(error_steady)}
    """
    
    axes[1, 1].text(0.1, 0.5, stats_text, fontsize=12, family='monospace',
                    verticalalignment='center')
    
    plt.tight_layout()
    return fig

def main():
    # File names
    input_file = 'am_input.dat'
    output_file = 'am_output.dat'
    message_file = 'message_signal.dat'
    
    # Check if files exist
    files = [input_file, output_file, message_file]
    missing_files = [f for f in files if not os.path.exists(f)]
    
    if missing_files:
        print("Error: Missing data files:")
        for f in missing_files:
            print(f"  - {f}")
        print("\nPlease run the testbench first to generate the data files.")
        sys.exit(1)
    
    print("Reading data files...")
    indices_in, am_input = read_data_file(input_file)
    indices_out, output = read_data_file(output_file)
    indices_msg, message = read_data_file(message_file)
    
    if am_input is None or output is None or message is None:
        print("Error: Could not read one or more data files.")
        sys.exit(1)
    
    # Sampling rate (from testbench)
    SAMPLE_RATE = 480000.0
    
    print(f"Loaded {len(am_input)} samples")
    print(f"Sample rate: {SAMPLE_RATE} Hz")
    print("\nGenerating plots...")
    
    # Generate plots
    fig1 = plot_time_domain(indices_out, am_input, output, message, SAMPLE_RATE)
    print("  ✓ Time domain plot created")
    
    fig2 = plot_frequency_domain(output, message, SAMPLE_RATE)
    print("  ✓ Frequency domain plot created")
    
    fig3 = plot_error_statistics(output, message)
    print("  ✓ Error analysis plot created")
    
    # Save figures
    print("\nSaving plots...")
    fig1.savefig('am_demod_time_domain.png', dpi=300, bbox_inches='tight')
    print("  ✓ Saved: am_demod_time_domain.png")
    
    fig2.savefig('am_demod_frequency_domain.png', dpi=300, bbox_inches='tight')
    print("  ✓ Saved: am_demod_frequency_domain.png")
    
    fig3.savefig('am_demod_error_analysis.png', dpi=300, bbox_inches='tight')
    print("  ✓ Saved: am_demod_error_analysis.png")
    
    print("\n✓ All plots generated successfully!")
    print("\nDisplaying plots...")
    plt.show()

if __name__ == '__main__':
    main()
